#!/usr/bin/env bash
# Verify the 1000 events generated by generate-events.sh landed in VictoriaLogs,
# with PII redaction applied.
set -euo pipefail

VL_URL="${VL_URL:-http://127.0.0.1:9428}"

sleep 5  # vector flush buffer

vl_count() {
  # $1 = LogsQL query string. Returns line count of NDJSON response.
  curl -sS "${VL_URL}/select/logsql/query" --data-urlencode "query=$1" | grep -c . || true
}

echo "=== Counts ==="
total=$(vl_count "service:demo-svc")
echo "Total demo-svc events: $total (expect >= 1000)"
[ "$total" -ge 1000 ] || { echo "FAIL: count below 1000"; exit 1; }

echo "=== PII redaction ==="
leaked_email=$(vl_count 'service:demo-svc AND _msg:"admin@example.com"')
echo "Raw email occurrences: $leaked_email (expect 0)"
[ "$leaked_email" -eq 0 ] || { echo "FAIL: PII email leaked"; exit 1; }

masked_email=$(vl_count 'service:demo-svc AND _msg:"<EMAIL>"')
echo "Masked <EMAIL> occurrences: $masked_email (expect >= 1)"
[ "$masked_email" -ge 1 ] || { echo "FAIL: email mask missing"; exit 1; }

leaked_ip=$(vl_count 'service:demo-svc AND _msg:"192.168.1.50"')
echo "Raw private IP occurrences: $leaked_ip (expect 0)"
[ "$leaked_ip" -eq 0 ] || { echo "FAIL: PII IP leaked"; exit 1; }

masked_ip=$(vl_count 'service:demo-svc AND _msg:"<PRIV_IP>"')
echo "Masked <PRIV_IP> occurrences: $masked_ip (expect >= 1)"
[ "$masked_ip" -ge 1 ] || { echo "FAIL: IP mask missing"; exit 1; }

echo
echo "=== OK: all assertions passed ==="
