#!/usr/bin/env bash
# Install ragstack.service systemd unit + env file pointing to current infra/ dir.
#
# Usage:
#   sudo bash install-systemd-unit.sh
#
# Detects:
#   - RAGSTACK_DIR = absolute path of infra/ chứa script này
#   - RAGSTACK_USER/GROUP = SUDO_USER (hoặc owner của infra dir)
set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "Run with sudo." >&2
  exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
UNIT_SRC="$INFRA_DIR/systemd/ragstack.service"
UNIT_DST=/etc/systemd/system/ragstack.service
ENV_DST=/etc/onelog-ragstack.env

OWNER_USER="${SUDO_USER:-$(stat -c %U "$INFRA_DIR")}"
OWNER_GROUP="$(id -gn "$OWNER_USER")"

echo "Detected:"
echo "  RAGSTACK_DIR   = $INFRA_DIR"
echo "  RAGSTACK_USER  = $OWNER_USER"
echo "  RAGSTACK_GROUP = $OWNER_GROUP"

cat > "$ENV_DST" <<EOF
# Auto-generated by install-systemd-unit.sh — $(date -Is)
RAGSTACK_DIR=$INFRA_DIR
RAGSTACK_USER=$OWNER_USER
RAGSTACK_GROUP=$OWNER_GROUP
EOF
chmod 0644 "$ENV_DST"

cp "$UNIT_SRC" "$UNIT_DST"
systemctl daemon-reload
systemctl enable ragstack.service

echo
echo "✓ Installed systemd unit. Auto-start enabled."
echo
echo "Lưu ý: KHÔNG \`systemctl start ragstack\` ngay nếu stack đang chạy thủ công"
echo "       (sẽ down + up lại). Để verify, reboot VM hoặc start sau khi compose down."
echo
echo "Inspect:"
echo "  systemctl cat ragstack.service"
echo "  cat $ENV_DST"
