#!/usr/bin/env bash
# pin-images.sh — extract exact image tags + sha256 digests of currently-running
# OneLog containers and print a ready-to-paste .env block. Prod hygiene: run this
# after verifying the stack is healthy → paste output into infra/.env → next
# `docker compose up -d` will use pinned images (no silent upstream breakage).
#
# Usage:
#   bash pin-images.sh              # prints tag lines (human-friendly)
#   bash pin-images.sh --digest     # prints image@sha256:… lines (immutable)
#
# Why both modes:
#   - Tag mode: readable, ties to upstream release; still resolves to whatever
#     that tag POINTS to today. Good default for most services.
#   - Digest mode: absolute lock; recommended for base infra (VL, Qdrant, NATS,
#     vmalert, alertmanager) where silent tag re-push would ruin the day.
set -euo pipefail

MODE="tag"
[[ "${1:-}" == "--digest" ]] && MODE="digest"

# Map container_name → .env var name (only images that have a *_IMAGE_TAG knob).
declare -A MAP=(
  [ragstack-vl]=VL_IMAGE_TAG
  [ragstack-qdrant]=QDRANT_IMAGE_TAG
  [ragstack-vmalert]=VMALERT_IMAGE_TAG
  [ragstack-alertmanager]=ALERTMANAGER_IMAGE_TAG
  [ragstack-nats]=NATS_IMAGE_TAG
  [ragstack-vector]=VECTOR_IMAGE_TAG
  [ragstack-litellm]=LITELLM_IMAGE_TAG
  [ragstack-openwebui]=OPENWEBUI_IMAGE_TAG
  [ragstack-mcpo]=MCPO_IMAGE_TAG
  [ragstack-mcp-vl]=MCPVL_IMAGE_TAG
  [ragstack-grafana]=GRAFANA_IMAGE_TAG
  # Caddy is a moving alpine target; still emit for completeness.
  [ragstack-caddy]=CADDY_IMAGE_TAG
)

echo "# --- Generated by pin-images.sh @ $(date -Iseconds) ---"
echo "# Paste into infra/.env to lock currently-running versions."
echo "# Mode: $MODE"
echo

for CTR in "${!MAP[@]}"; do
  VAR="${MAP[$CTR]}"
  if ! docker inspect "$CTR" >/dev/null 2>&1; then
    echo "# ${VAR}=<container $CTR not running — skipped>"
    continue
  fi

  # Config.Image = tag as declared (e.g. qdrant/qdrant:v1.12.5)
  # Image        = sha256:... local digest (immutable)
  # RepoDigests  = registry-verifiable image@sha256:...
  IMG_TAG=$(docker inspect --format '{{.Config.Image}}' "$CTR")
  # Strip repo prefix, keep just the :tag part after the last colon (or "latest").
  TAG_ONLY="${IMG_TAG##*:}"
  [[ "$TAG_ONLY" == "$IMG_TAG" ]] && TAG_ONLY=latest

  if [[ "$MODE" == "digest" ]]; then
    # Use RepoDigests[0] if present (pulled from registry), else Image (local).
    DIGEST=$(docker inspect --format '{{if .RepoDigests}}{{index .RepoDigests 0}}{{end}}' "$CTR")
    if [[ -n "$DIGEST" ]]; then
      # Format: repo@sha256:...  → keep the @sha256:... suffix as the "tag"
      SHA="${DIGEST#*@}"
      echo "${VAR}=${TAG_ONLY}@${SHA}"
    else
      echo "# ${VAR}=${TAG_ONLY}  # no RepoDigest (image built locally?)"
    fi
  else
    echo "${VAR}=${TAG_ONLY}"
  fi
done

echo
echo "# Verify after paste:  docker compose config | grep image:"
