#!/usr/bin/env bash
# Setup rsyslog client → onelog logserver forwarding (TCP 6514, RFC5424).
#
# Usage:
#   sudo LOG_SERVER_IP=192.168.122.53 bash setup-rsyslog-client.sh
#
# What it does:
#   1. Install rsyslog if missing
#   2. Disable any conflicting forwarder files in /etc/rsyslog.d/
#   3. Drop a known-good 90-forward-onelog.conf (TCP + queue + RFC5424 template)
#   4. Syntax-check, restart rsyslog, verify TCP connection
#   5. Fire a smoke log + suggest verification command on logserver
#
# Why TCP 6514 (not default UDP 514):
#   - Vector strict syslog parser rejects rsyslog's default RFC3164 (no year + tz)
#   - TCP gives reliable delivery + disk-queue resume after logserver restart
#   - Standard port for syslog-tls; later swap to TLS without changing topology
set -euo pipefail

LOG_SERVER_IP="${LOG_SERVER_IP:?Set LOG_SERVER_IP=<logserver ip>, e.g. 192.168.122.53}"
LOG_SERVER_PORT="${LOG_SERVER_PORT:-6514}"
CONF=/etc/rsyslog.d/90-forward-onelog.conf

if [[ $EUID -ne 0 ]]; then
  echo "Run with sudo." >&2
  exit 1
fi

# ---------- [1/5] Ensure rsyslog installed ----------
echo "[1/5] Ensure rsyslog installed"
if ! command -v rsyslogd >/dev/null 2>&1; then
  apt-get update -y
  apt-get install -y rsyslog
fi
systemctl enable rsyslog >/dev/null 2>&1 || true

# ---------- [2/5] Disable any prior forwarder configs ----------
echo "[2/5] Backup conflicting forwarder configs trong /etc/rsyslog.d/"
for f in /etc/rsyslog.d/*-forward*.conf /etc/rsyslog.d/*-onelog*.conf; do
  [[ -f "$f" && "$f" != "$CONF" ]] || continue
  echo "  Backup: $f → $f.bak"
  mv "$f" "$f.bak"
done

# ---------- [3/5] Write known-good config ----------
echo "[3/5] Write $CONF"
cat > "$CONF" <<EOF
# Generated by setup-rsyslog-client.sh — forward to onelog logserver
# TCP 6514 + RFC5424 template (Vector strict parser yêu cầu)
#
# Reload:  sudo systemctl restart rsyslog
# Verify:  ss -tnp | grep ':${LOG_SERVER_PORT}'   # ESTAB tới ${LOG_SERVER_IP}

template(name="ragstack_fmt" type="string"
  string="<%PRI%>1 %TIMESTAMP:::date-rfc3339% %HOSTNAME% %APP-NAME% %PROCID% %MSGID% - %msg%\n"
)

*.* action(type="omfwd"
  target="${LOG_SERVER_IP}"
  port="${LOG_SERVER_PORT}"
  protocol="tcp"
  template="ragstack_fmt"
  action.resumeRetryCount="-1"
  queue.type="LinkedList"
  queue.size="10000"
  queue.filename="onelog_fwd"
  queue.saveOnShutdown="on"
  queue.maxDiskSpace="500m"
)
EOF

# ---------- [4/5] Syntax check + restart ----------
echo "[4/5] Syntax check"
if ! rsyslogd -N1 2>&1 | tee /tmp/rsyslog-check.log | grep -qE 'error|fail'; then
  echo "  ✓ Config syntax OK"
else
  echo "  ✗ Config has errors:"
  grep -iE 'error|fail' /tmp/rsyslog-check.log
  exit 2
fi

echo "  Restart rsyslog"
systemctl restart rsyslog
sleep 2
systemctl is-active --quiet rsyslog || { echo "rsyslog failed to start"; exit 3; }

# ---------- [5/5] Verify TCP connection ----------
echo "[5/5] Verify forward chain"
if ss -tnp 2>/dev/null | grep -q ":${LOG_SERVER_PORT}"; then
  echo "  ✓ TCP connection ESTABLISHED tới ${LOG_SERVER_IP}:${LOG_SERVER_PORT}"
else
  echo "  ⚠️  Chưa thấy TCP conn — có thể logserver chưa accept hoặc UFW chặn."
  echo "      Test thủ công: timeout 3 bash -c 'cat </dev/tcp/${LOG_SERVER_IP}/${LOG_SERVER_PORT}' && echo OK"
fi

logger -t client-onboard "Setup verified $(date -Is) from $(hostname)"
echo "  Fired test log: 'service:client-onboard'"
echo
echo "Trên logserver chạy verify:"
echo "  curl 'http://localhost:9428/select/logsql/query?query=service:client-onboard&limit=5'"
