apiVersion: 1

datasources:
  - name: VictoriaLogs
    type: victoriametrics-logs-datasource
    uid: victorialogs
    url: http://victorialogs:9428
    access: proxy
    isDefault: true
    editable: false
